### ISSUE TITLE
Remove Recovery Services Vault  -> Get-AzRecoveryServicesBackupContainer: A parameter cannot be found that matches parameter name 'Status'.

### ISSUE THREAD

**Issue by benderke** [libre-devops/libredevops-dot-org#1]
Since I'm lazy I just run the script in the azure portal shell.  I needed to remove the "-Status Registered" parameter for the Get-AzRecoveryServicesBackupContainer  function because I got the error:  A parameter cannot be found that matches parameter name 'Status'.

Just wanted to let you know so you might could update / double check the script. 

```
PS /home/XXXXXX> Get-AzRecoveryServicesBackupContainer -ContainerType AzureVMAppContainer -Status Registered -VaultId $VaultToDelete.ID | Where-Object {$_.ExtendedInfo.WorkloadType -eq "SQL"}

Get-AzRecoveryServicesBackupContainer: A parameter cannot be found that matches parameter name 'Status'.
```

**Comment by craigthackerx** [comment]
Thanks for raising the issue!, I didn't even see this come through on my emails, so apologies for the late reply.  That should be it updated now.
